### ISSUE TITLE
not possible to run different methods simultaneously.

### ISSUE THREAD

**Issue by qkrybin** [dsrvlabs/vatz#310]
### Checklist
- [ ] Bug from Service (Vatz)
- [x] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
I edited default.yaml according to the guide. And there was a field to write down the port number.
<img width="772" alt="image" src="https://user-images.githubusercontent.com/63234878/203267797-ada02a52-f7e1-4920-bc9c-46bc49ce333a.png">

There were three methods of vatz-plugin-sysutil, all running on different ports.
When I chose one port number for the method, the other method didn't report the outcome.
So, I was confused about which one I should write on plugin_port.
Can't I use all methods at the same time? Or do I have to switch the number every time I use a different method?

### **How to Reproduce**

1. Go to 'default.yaml' and edit plugin_port 
```
 30   plugins:
 31     - plugin_name: "vatz-plugin-sysutil"
 32       plugin_address: "localhost"
 33       plugin_port: 9096
 34       executable_methods:
 35         - method_name: "cpu_monitor"
 36         - method_name: "mem_monitor"
 37         - method_name: "disk_monitor"'
```
2. run sysutil methods and vatz

### **Expected behavior**
I expected CPU, disk, and memory to be monitored simultaneously.

### **Screenshots**
Not proceed..!

<img width="523" alt="image" src="https://user-images.githubusercontent.com/63234878/203258931-9dcad6aa-ca1f-4e21-bea0-a6e0d51317a5.png">

**Comment by xellos00** [comment]
@qkrybin 
there's yaml file that has to be in format to pass each values. 
single plugin does has single method in purpose of start/stop plugin without off the VATZ
so correct form is 

```
plugins_infos:
  default_verify_interval: 15
  default_execute_interval: 30
  default_plugin_name: "vatz-plugin"
  plugins:
    - plugin_name: "cpu-monitor"
      plugin_address: "localhost"
      plugin_port: 9093
      executable_methods:
        - method_name: "getCPUUsage"
    - plugin_name: "disk-monitor"
      plugin_address: "localhost"
      plugin_port: 9094
      executable_methods:
        - method_name: "getDISKUsage"
    - plugin_name: "mem-monitor"
      plugin_address: "localhost"
      plugin_port: 9095
      executable_methods:
        - method_name: "getMEMUsage"
    - plugin_name: "is_alive"
      plugin_address: "localhost"
      plugin_port: 9098
      executable_methods:
        - method_name: "cosmoshub-is-alive"
```
