### ISSUE TITLE
Store plugin's executing information

### ISSUE THREAD

**Issue by rootwarp** [dsrvlabs/vatz#388]
## Checklist
- [X] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [ ] Enhancement on Vatz
- [ ] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
> A clear description of what feature need to be developed or enhanced in Vatz 

When a plugin is executed, executing information should be managed in SQLite for maintenance reason.

### **Describe the output that you are expecting for above**
> A clear and concise description of what you expect to happen.

- When the plugin is started, PID will be stored in SQLite.
- When VATZ is started, it will check plugin processes by stored PID and update DB.
- PID will be used to stop the plugin.

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

N/A

### **Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by rootwarp** [comment]
@xellos00 As you know, we are not storing executing information of the plugin.
And I think it could be better to store and track information at the DB.

For the starting point, I'll track the PID of the plugin. Do you have any other ideas to store?

**Comment by xellos00** [comment]
> 
@rootwarp 
Guess that's best idea, no matter what I think it's a requirement to set up DB. 
but Let's have a meeting at some point. I will ping you. 
for more discussions.

**Comment by xellos00** [comment]
Plugin info - config - DB

-- 
AS-IS
VATZ get <- Config

To-BE
Config push -> DB
VATZ get <- DB

**Comment by xellos00** [comment]
> Plugin info - config - DB
> 
> * AS-IS
>   VATZ get <- Config
> * To-BE
>   Config push -> DB
>   VATZ get <- DB
> 
> CLI STOP, KILL enable/disable
> 
> @meetrick Good to see through DB get .

Let's put a vote. 
- AS-IS 👍🏽 
- To-Be ❤️

**Comment by xellos00** [comment]
> > Plugin info - config - DB
> > 
> > * AS-IS
> >   VATZ get <- Config
> > * To-BE
> >   Config push -> DB
> >   VATZ get <- DB
> > 
> > CLI STOP, KILL enable/disable
> > @meetrick Good to see through DB get .
> 
> Let's put a vote.
> 
> * AS-IS 👍🏽
> * To-BE ❤️

Output by vote
> To-BE
> Config push -> DB
> VATZ get <- DB

**Comment by xellos00** [comment]
@rootwarp 
As we previously vote, I will take this issue to migration feature config.yaml.

**Comment by xellos00** [comment]
Tasks
- [ ] Store `Config.yaml` into DB
- [ ] Update DB schema from previous version to New Schema
- [ ] Update VATZ to read every config value from DB

**Comment by xellos00** [comment]
```
vatz_protocol_info:
  protocol_identifier: "Certik(shentu)"
  port: 8080
  health_checker_schedule:
    - "0 1 * * *"
  notification_info:
    host_name: "ybl-certik-mainnet-validator-do-frankfurt"
    default_reminder_schedule:
      - "*/30 * * * *"
    dispatch_channels:
      - channel: "discord"
        secret: "https://discord.com/api/webhooks/1040514961547477082/lQG92N_wq5SU4Z-oRvgD1F7QiFxOMQ6EYteVfZAWGJj9uaoV87vAqU3q6a59TV2vxS8O"
      - channel: "pagerduty"
        secret: "7cb00cea9afe4606d0315d4de7a1a521"
      - channel: "telegram"
        secret: "5306030270:AAF0jyroEdJdiFQ1TtprxLOIY5M2JR3E7CY"
        chat_id: "-1001508290262"
plugins_infos:
  default_verify_interval: 15
  default_execute_interval: 30
  default_plugin_name: "vatz-plugin"
  plugins:
    - plugin_name: "cpu-monitor"
      plugin_address: "localhost"
      plugin_port: 9094
      executable_methods:
        - method_name: "getCPUUsage"
    - plugin_name: "disk-monitor"
      plugin_address: "localhost"
      plugin_port: 9096
      executable_methods:
        - method_name: "getDISKUsage"
    - plugin_name: "mem-monitor"
      plugin_address: "localhost"
      plugin_port: 9095
      executable_methods:
        - method_name: "getMEMUsage"
    - plugin_name: "peer_count"
      plugin_address: "localhost"
      plugin_port: 9099
      executable_methods:
        - method_name: "cosmoshub-peer-count"
    - plugin_name: "block_sync"
      plugin_address: "localhost"
      plugin_port: 9100
      executable_methods:
        - method_name: "BlockSync"
```

**Comment by xellos00** [comment]
1. Yaml 파일에 있는 것은 DB 에 넣지 않는다. 
   1.1 각 Config yaml은 따로 DB 에 저장하지 않는다. 
   1.2  추후에 각 사용성과 기능을 생각해 다시 회의를 진행한다.   

---

@xellos00 
- Plugin_info Schema Update
- Enable/Disable CLIs

----
@rootwarp & @xellos00 
- Delete CLI process
- DB Migration.

**Comment by xellos00** [comment]
```


vatz_protocol_info:
  protocol_identifier: "Certik(shentu)"
  port: 8080
  health_checker_schedule:
    - "0 1 * * *"
  notification_info:
    host_name: "ybl-certik-mainnet-validator-do-frankfurt"
    default_reminder_schedule:
      - "*/30 * * * *"
    dispatch_channels:
      - channel: "discord"
        secret: "https://discord.com/api/webhooks/1040514961547477082/lQG92N_wq5SU4Z-oRvgD1F7QiFxOMQ6EYte345VfZAWGJj9uaoV87vAqU3q6a2259TV2vxS8O"
      - channel: "pagerduty"
        secret: "7cb00cea9afe4606d0315d41234de7a1a521"
      - channel: "telegram"
        secret: "5306030270:AAF0jyroEdJ123diFQ1TtprxLOIY5M2JR3E7CY"
        chat_id: "-1001508290262"
plugins_infos:
  default_verify_interval: 15
  default_execute_interval: 30
  default_plugin_name: "vatz-plugin"
  plugins:
    - plugin_name: "cpu-monitor"
      plugin_address: "localhost"
      plugin_port: 9094
      executable_methods:
        - method_name: "getCPUUsage"
    - plugin_name: "disk-monitor"
      plugin_address: "localhost"
      plugin_port: 9096
      executable_methods:
        - method_name: "getDISKUsage"
    - plugin_name: "mem-monitor"
      plugin_address: "localhost"
      plugin_port: 9095
      executable_methods:
        - method_name: "getMEMUsage"
    - plugin_name: "peer_count"
      plugin_address: "localhost"
      plugin_port: 9099
      executable_methods:
        - method_name: "cosmoshub-peer-count"
    - plugin_name: "block_sync"
      plugin_address: "localhost"
      plugin_port: 9100
      executable_methods:
        - method_name: "BlockSync"
```
