### ISSUE TITLE
CI operation that create VATZ weekly meeting 

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#417]
### **What does it require to on Vatz**
> A clear and concise description of what you expected to happen through Ci/CD

No automatic register process VATZ weekly sync on discussion per bi-weekly. 

### **Expected behavior**
> A clear and concise description of results after CI/CD implementation.

Create a new `General` discussion every two weeks automatically. 

1. Register new milestone that includes
   - #number of milestone
   - Due date on milestone. 

2. Include Screenshot if possible. 
3. Add template on that. 

### **How to run**
> Please, Update and give simple guide to run CI/CD process with this issue. 

No action requires to run discussion. 

### **Screenshots**
> If applicable, add screenshots to help explain your problem

**Comment by xellos00** [comment]
@gnongs 
Can you handle this issue as you did on Validator?

**Comment by gnongs** [comment]
> @gnongs Can you handle this issue as you did on Validator?

Okay. I will try it!

**Comment by gnongs** [comment]
> Test repository: https://github.com/gnongs/create-discussion

**Comment by gnongs** [comment]
## Obtain `repository-id` and `category-id`
> Link: https://docs.github.com/en/graphql/overview/explorer

```
query MyQuery {
  repository(name: "<REPO_NAME>", owner: "<REPO_OWNER>") {
    id
    discussionCategories(first: 10) {
      edges {
        node {
          id
          name
        }
        cursor
      }
    }
  }
}
```

**Comment by gnongs** [comment]
```sh
$ gh workflow run create-discussion.yml
```

**Comment by gnongs** [comment]
## Generated

> https://github.com/gnongs/create-discussion/discussions/3

![image](https://github.com/dsrvlabs/vatz/assets/65050483/c1252e2d-944a-4ea1-911e-98355b807daa)

**Comment by gnongs** [comment]
What is template?

**Comment by xellos00** [comment]
@gnongs 

> * What is template?
> * What time do you want to create a discussion & milestone? UTC
> * Should I close the previous milestone? You don't have to 
> Please create one, when VATZ bi-weekly meeting is over.

**Comment by gnongs** [comment]
@xellos00 
Currently, making Discussion and creating Milestone githubaction are ready.
> Action link: https://github.com/gnongs/create-discussion/actions/runs/4946512567

<img width="931" alt="image" src="https://github.com/dsrvlabs/vatz/assets/65050483/31442edf-3f8a-485c-9902-7a6db0bbdb2e">

<img width="1239" alt="image" src="https://github.com/dsrvlabs/vatz/assets/65050483/a6fa24b8-e4ac-4f45-ae87-c421904ed5f4">

If you answer the above, I think we can finish the issue by correcting it accordingly.

**Comment by gnongs** [comment]
## Before we apply

We need to set below value on repository.
1. Go to https://docs.github.com/ko/graphql/overview/explorer
2. Run below query
```
query MyQuery {
  repository(name: "vatz", owner: "dsrvlabs") {
    id
    discussionCategories(first: 10) {
      edges {
        node {
          id
          name
        }
        cursor
      }
    }
  }
}
```
3. Set value on repository secret
```sh
DISCUSSION_REPO_ID=
DISCUSSION_CATE_ID=
```

**Comment by xellos00** [comment]
> ## Before we apply
> We need to set below value on repository.
> 
> 1. Go to https://docs.github.com/ko/graphql/overview/explorer
> 2. Run below query
> 
> ```
> query MyQuery {
>   repository(name: "vatz", owner: "dsrvlabs") {
>     id
>     discussionCategories(first: 10) {
>       edges {
>         node {
>           id
>           name
>         }
>         cursor
>       }
>     }
>   }
> }
> ```
> 
> 3. Set value on repository secret
> 
> ```shell
> DISCUSSION_REPO_ID= #data.repository.id
> DISCUSSION_CATE_ID= #data.repository.discussionCategories.edges[1].node.id
> ```
> 
> @xellos00 Could you proceed above steps? If you don't understand something, please feel free to ask.

@xellos00 
Can you give me a call when you are available for this week? 
let's go over together and check its working status together.

**Comment by gnongs** [comment]
> @xellos00 Can you give me a call when you are available for this week? let's go over together and check its working status together.

@xellos00 Then how about tomorrow at 10 am (KST)?

**Comment by xellos00** [comment]
```
name: Add Label to Discussion

on:
  issues:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github/get-discussion@v1
        with:
          issue_number: ${{ github.event.issue.number }}

      - uses: actions/github/list-labels@v1
        with:
          discussion_id: ${{ steps.get-discussion.outputs.discussion_id }}

      - uses: actions/github/add-label@v1
        with:
          label: ${{ steps.list-labels.outputs.labels[0] }}
          discussion_id: ${{ steps.get-discussion.outputs.discussion_id }}

```
