### ISSUE TITLE
Auto Discussion creating is kept failing 

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#560]
### Checklist
- [ ] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [x] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
> A clear and concise description of what the bug is.

<img width="1661" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/d15cb32e-101d-4852-856e-14e8fcf3d70b">

### **How to Reproduce**
> Steps to reproduce the behavior:

1. Go to https://github.com/dsrvlabs/vatz/actions/runs/9192828634

### **Expected behavior**
> A clear and concise description of what you expected to happen.

### **Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by gnongs** [comment]
@xellos00 
Can I set the github action like below?
- Create a Discussion and Milestone by the every 2 week

**Comment by gnongs** [comment]
@xellos00 
It is working well at this time. If action printed error logs, I will handle it.

**Comment by xellos00** [comment]
> @xellos00 
> 
> It is working well at this time. If action printed error logs, I will handle it.

how did you confirm it works properly working? did you created new discussion with this?

**Comment by gnongs** [comment]
@xellos00 Sorry, I missed to check the action. That has some bugs. I will fix it!

**Comment by xellos00** [comment]
> @xellos00 Sorry, I missed to check the action. That has some bugs. I will fix it!

@gnongs 
it's been a while, Do you have any update or progress for this issue?

**Comment by gnongs** [comment]
@xellos00 Currently I'm testing CI code on my local.

```yaml
name: Create a next vatz discussion & milestone
on:
  workflow_dispatch:
    #  schedule:
    #    - cron: "0 2 * * 2" # Every Tuesday at 10:00:00.
  push:
    branches:
      - main

env:
  START_DATE: "2024-06-05"
  URL: https://api.github.com/repos/dsrvlabs/vatz/milestones
  TOKEN: <TOKEN>

jobs:
  create_bi_weekly:
    runs-on: ubuntu-latest
    steps:
    - name: Check creation date # Step to determine if this is the second week because you have to create a 'Discussion & Milestone' every two weeks
      id: check_week
      run: |
        WEEK_NUM=`date -d ${{ env.START_DATE }} +%U`
        if [ $(( WEEK_NUM % 2)) -eq 0 ]; then
          echo "This is the correct week"
          echo "::set-output name=run_job::true"
        else
          echo "This is not the correct week"
          echo "::set-output name=run_job::false"
        fi
      shell: bash

    - name: Get latest discussion number
      if: steps.check_week.outputs.run_job == 'true'
      id: check_latest_discussion
      run: |
        # GitHub GraphQL API Endpoint
        URL="https://api.github.com/graphql"

        # GraphQL Query
        QUERY='{
          "query": "query { repository(owner: \"dsrvlabs\", name: \"vatz\") { discussions(first: 1, orderBy: {field: CREATED_AT, direction: DESC}) { nodes { title url createdAt author { login } } } } }"
        }'

        # Sending the request using curl
        response=$(curl -s -X POST -H "Authorization: bearer ${{ env.TOKEN }}" -H "Content-Type: application/json" -d "$QUERY" $URL)

        LASTEST=`echo $response | jq .data.repository.discussions.nodes[0].title | awk '{print $1 }' | sed 's/\"//g' | sed 's/\.//g'`
        echo "::set-output name=run_job::$LASTEST"
      shell: bash

    - name: Generate new discussion
      if: steps.check_latest_discussion.outputs.run_job != ''
      id: create_discussion
      uses: abirismyname/create-discussion@v1.1.0
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "${{ steps.check_latest_discussion.outputs.run_job }}. VATZ biweekly meeting at ${{ env.DUE_DATE }}"
        body: |
          ### 1. Overall
          ### 2. Statistic Rate

          Sprint | Issue fulfillment | progress rate(%)
          --: | :--: | :--:

        repository-id: "${{ secrets.DISCUSSION_REPO_ID }}"
        category-id: "${{ secrets.DISCUSSION_CATE_ID }}"

          #    - name: Generate new milestone
          #      id: create_milestone
          #      run: |
          #        echo "Due Date: ${{ env.DUE_DATE }}"
          #        echo "Next milestone number: ${{ env.NEXT_MILESTONE_NUMBER }}"
          #        curl -s \
          #          -X POST \
          #          -H "Accept: application/vnd.github.v3+json" \
          #          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          #          "${{ env.URL }}" \
          #          -d '{"title":"Sprint '${{ env.NEXT_MILESTONE_NUMBER }}' (~ '${{ env.DUE_DATE }}')","description":" ","state":"open","due_on":"'${{ env.DUE_DATE_LONG }}'"}'
```

I think this test will finish at tomorrow. Sorry for delaying 🙏
