### ISSUE TITLE
Multi receiver notification per plugins

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#583]
## Checklist
- [x] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [ ] Enhancement on Vatz
- [ ] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
> A clear description of what feature need to be developed or enhanced in Vatz 

for watcher plugins, it there must be a feature that conduct an multi notifications for more. 
```
vatz_protocol_info:
  home_path: "~/.vatz"
  protocol_identifier: "xellosDK"
  port: 9090
  health_check_info:
    default_health_checker_schedule:
      - "0 1 * * *"
  notification_info:
    host_name: "hyperlane-mainnet-validator12-aaa-aws-frankfurt"
    default_reminder_schedule:
      - "*/30 * * * *"
    dispatch_channels:
      - channel: "telegram"
        secret: "yyyyy"
        flag: "for_near"
      - channel: "slack"
        secret: "xxxxxx
        flag: "for_flow"
  rpc_info:
    enabled: true
    address: "127.0.0.1"
    grpc_port: 19090
    http_port: 19091
  monitoring_info:
    gcp:
      gcp_cloud_logging_info:
        enabled: true
        cloud_logging_credential_info:
          project_id: "samplePro"
          credentials_type: "SAC"
          credentials: "https://vatzaaaaaple.json"
          checker_schedule:
            - "* * * * *"
    prometheus:
      enabled: true
      address: "127.0.0.1"
      port: 18080
plugins_infos:
  default_verify_interval: 6
  default_execute_interval: 8
  default_plugin_name: "vatz-plugin"
  plugins:
    - plugin_name: "cpu_monitor"
      plugin_address: "localhost"
      plugin_port: 9001
      executable_methods:
        - method_name: "node_watcher"
      option: 
        - noti_flag: "for_near"
    - plugin_name: "cpu_monitor"
      plugin_address: "localhost"
      plugin_port: 9002
      executable_methods:
        - method_name: "node_watcher"
      option: 
        - noti_flag: "for_flow"

```

### **Describe the output that you are expecting for above**
> A clear and concise description of what you expect to happen.

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

### **Additional context**
> Add any other context or screenshots about the feature request here.
